depr(command) Remove the hoa:paste command.
hoaproject/Devtools pull request #56
Opened 2018-02-23 10:30 UTC by shulard

Since we choose to do not migration the Paste repository, this command is now deprecated.

2018-02-23 13:40 UTC, Hywan approved these changes

2018-02-23 17:32 UTC, vonglasow commented
@shulard thanks for the PR.

Could you delete also the documentation in README.md file? Thanks

2018-02-23 17:33 UTC, vonglasow requested changes
Delete the doc in README file ;)

2018-02-23 18:01 UTC, shulard commented
I've removed reference to the `paste` command from the README file.

2018-05-24 09:59 UTC, vonglasow approved these changes

2018-05-24 11:57 UTC, Hywan approved these changes

2018-05-24 12:04 UTC, merged