Generate path for FlexEntity and class_alias
hoaproject/Devtools pull request #6
Opened 2015-02-10 21:49 UTC by camael24

2015-02-11 07:50 UTC, Hywan commented on Bin/Stub.php
> +                $porcelaine = true;
`porcelain`, not `porcelaine`, and it's not that, it's `dryRun`. `porcelain` is different :-).

2015-02-11 07:51 UTC, Hywan commented on Bin/Stub.php
> +use Hoa\Console;
`use Hoa\File;`

2015-02-11 07:51 UTC, Hywan commented on Bin/Stub.php
> +        $finder = new \Hoa\File\Finder();
`$finder = new File\Finder();`

2015-02-11 07:51 UTC, Hywan commented on Bin/Stub.php
> +        $f = array();
Use short-array syntax here :-).

2015-02-11 07:52 UTC, Hywan commented on Bin/Stub.php
> +        foreach ($finder as $key => $value) {
We never use `$key`, do not declare it :-).

2015-02-11 07:53 UTC, Hywan commented on Bin/Stub.php
> +use Hoa\Console;
`use Hoa\Core;`

2015-02-11 07:53 UTC, Hywan commented on Bin/Stub.php
> +                    $end = \Hoa\Core\Consistency\Consistency::getEntityShortestName($c);
`$end = Core\Consistency…;`

2015-02-11 07:53 UTC, Hywan commented on Bin/Stub.php
> +                    $f[] = array('class' => str_replace('/', '\\', $name), 'alias' => $end);
Use array short syntax :-).

2015-02-11 07:56 UTC, Hywan commented on Bin/Stub.php
> +class Stub extends \Hoa\Console\Dispatcher\Kit {
The name says nothing about what it really does :-/. (do not forget to update the help too).
Suggestion (but I am not sure!): `UnfoldClassAliases`?

2015-02-11 07:57 UTC, Hywan commented
@camael24 Could you provide a description and an example of use please? Also, I am not certain to be the one to evaluate this PR. Do you know someone else who could do a peer-review?

2015-02-11 08:50 UTC, camael24 commented
@Hywan thanks to the review, i will apply those modification (not sure "ces modifications") tomorrow, today I too budy

The PR its to help the class_alias resolution in destination to our IDE, we juste need to include the generated file in exemple `/tmp/foo.php` in the IDE.

An output exemple file is : 
```
<?php 
namespace Hoa\Console {
class Readline extends \Hoa\Console\Readline\Readline {}
}
namespace Hoa\Console\Readline {
class Autocompleter extends \Hoa\Console\Readline\Autocompleter\Autocompleter {}
}
namespace Hoa {
class Console extends \Hoa\Console\Console {}
}
namespace Hoa {
class Prototype extends \Hoa\Prototype\Prototype {}
}
namespace Hoa {
class Memory extends \Hoa\Memory\Memory {}
}
namespace Hoa\Fastcgi {
class Exception extends \Hoa\Fastcgi\Exception\Exception {}
}
namespace Hoa\Cache {
class Backend extends \Hoa\Cache\Backend\Backend {}
}
namespace Hoa {
class Cache extends \Hoa\Cache\Cache {}
}
namespace Hoa\Cache {
class Frontend extends \Hoa\Cache\Frontend\Frontend {}
}
namespace Hoa\Core {
class Parameter extends \Hoa\Core\Parameter\Parameter {}
}
namespace Hoa\Core {
class Event extends \Hoa\Core\Event\Event {}
}
namespace Hoa\Core {
class Exception extends \Hoa\Core\Exception\Exception {}
}
namespace Hoa\Core {
class Consistency extends \Hoa\Core\Consistency\Consistency {}
}
namespace Hoa\Core {
class Protocol extends \Hoa\Core\Protocol\Protocol {}
}
namespace Hoa {
class Core extends \Hoa\Core\Core {}
}
namespace Hoa\Core {
class Data extends \Hoa\Core\Data\Data {}
}
namespace Hoa\Http {
class Response extends \Hoa\Http\Response\Response {}
}
namespace Hoa\Http {
class Exception extends \Hoa\Http\Exception\Exception {}
}
namespace Hoa {
class Http extends \Hoa\Http\Http {}
}
namespace Hoa\Database\Layer {
class Pdo extends \Hoa\Database\Layer\Pdo\Pdo {}
}
namespace Hoa\Database {
class Query extends \Hoa\Database\Query\Query {}
}
namespace Hoa {
class Praspel extends \Hoa\Praspel\Praspel {}
}
namespace Hoa\Praspel\Exception {
class Failure extends \Hoa\Praspel\Exception\Failure\Failure {}
}
namespace Hoa\Praspel {
class Exception extends \Hoa\Praspel\Exception\Exception {}
}
namespace Hoa\Praspel\Iterator {
class Coverage extends \Hoa\Praspel\Iterator\Coverage\Coverage {}
}
namespace Hoa\Praspel\Model {
class Variable extends \Hoa\Praspel\Model\Variable\Variable {}
}
namespace Hoa\Praspel {
class AssertionChecker extends \Hoa\Praspel\AssertionChecker\AssertionChecker {}
}
namespace Hoa {
class Session extends \Hoa\Session\Session {}
}
namespace Hoa\Session {
class Exception extends \Hoa\Session\Exception\Exception {}
}
namespace Hoa {
class Graph extends \Hoa\Graph\Graph {}
}
namespace Hoa {
class Locale extends \Hoa\Locale\Locale {}
}
namespace Hoa\Locale {
class Localizer extends \Hoa\Locale\Localizer\Localizer {}
}
namespace Hoa {
class Tree extends \Hoa\Tree\Tree {}
}
namespace Hoa\Math\Combinatorics {
class Combination extends \Hoa\Math\Combinatorics\Combination\Combination {}
}
namespace Hoa\Math {
class Exception extends \Hoa\Math\Exception\Exception {}
}
namespace Hoa\Math {
class Sampler extends \Hoa\Math\Sampler\Sampler {}
}
namespace Hoa\Compiler {
class Exception extends \Hoa\Compiler\Exception\Exception {}
}
namespace Hoa\Compiler\Llk {
class Rule extends \Hoa\Compiler\Llk\Rule\Rule {}
}
namespace Hoa\Compiler\Llk {
class Sampler extends \Hoa\Compiler\Llk\Sampler\Sampler {}
}
namespace Hoa\Compiler {
class Llk extends \Hoa\Compiler\Llk\Llk {}
}
namespace Hoa {
class Ruler extends \Hoa\Ruler\Ruler {}
}
namespace Hoa\Ruler {
class Exception extends \Hoa\Ruler\Exception\Exception {}
}
namespace Hoa\Ruler\Model {
class Bag extends \Hoa\Ruler\Model\Bag\Bag {}
}
namespace Hoa\Ruler {
class Model extends \Hoa\Ruler\Model\Model {}
}
namespace Hoa\Xyl {
class Element extends \Hoa\Xyl\Element\Element {}
}
namespace Hoa\Xyl\Interpreter {
class Html extends \Hoa\Xyl\Interpreter\Html\Html {}
}
namespace Hoa\Xyl {
class Interpreter extends \Hoa\Xyl\Interpreter\Interpreter {}
}
namespace Hoa {
class Xyl extends \Hoa\Xyl\Xyl {}
}
namespace Hoa\Realdom {
class Exception extends \Hoa\Realdom\Exception\Exception {}
}
namespace Hoa {
class Realdom extends \Hoa\Realdom\Realdom {}
}
namespace Hoa {
class Promise extends \Hoa\Promise\Promise {}
}
namespace Hoa {
class Bench extends \Hoa\Bench\Bench {}
}
namespace Hoa {
class Log extends \Hoa\Log\Log {}
}
namespace Hoa\Log {
class Backtrace extends \Hoa\Log\Backtrace\Backtrace {}
}
namespace Hoa {
class String extends \Hoa\String\String {}
}
namespace Hoa\Xml {
class Element extends \Hoa\Xml\Element\Element {}
}
namespace Hoa\Xml {
class Exception extends \Hoa\Xml\Exception\Exception {}
}
namespace Hoa {
class Xml extends \Hoa\Xml\Xml {}
}
namespace Hoa {
class Iterator extends \Hoa\Iterator\Iterator {}
}
namespace Hoa\Iterator {
class Recursive extends \Hoa\Iterator\Recursive\Recursive {}
}
namespace Hoa {
class   extends \Hoa\ \  {}
}
namespace Hoa {
class Dispatcher extends \Hoa\Dispatcher\Dispatcher {}
}
namespace Hoa\Mail {
class Exception extends \Hoa\Mail\Exception\Exception {}
}
namespace Hoa\Mail {
class Content extends \Hoa\Mail\Content\Content {}
}
namespace Hoa {
class Registry extends \Hoa\Registry\Registry {}
}
namespace Hoa {
class Model extends \Hoa\Model\Model {}
}
namespace Hoa\Router {
class Exception extends \Hoa\Router\Exception\Exception {}
}
namespace Hoa {
class Router extends \Hoa\Router\Router {}
}
namespace Hoa\Stream {
class Filter extends \Hoa\Stream\Filter\Filter {}
}
namespace Hoa {
class Stream extends \Hoa\Stream\Stream {}
}
namespace Hoa\Stream {
class Wrapper extends \Hoa\Stream\Wrapper\Wrapper {}
}
namespace Hoa\Stream\Wrapper {
class IWrapper extends \Hoa\Stream\Wrapper\IWrapper\IWrapper {}
}
namespace Hoa\Socket {
class Connection extends \Hoa\Socket\Connection\Connection {}
}
namespace Hoa {
class Socket extends \Hoa\Socket\Socket {}
}
namespace Hoa {
class Translate extends \Hoa\Translate\Translate {}
}
namespace Hoa {
class File extends \Hoa\File\File {}
}
namespace Hoa\File {
class Exception extends \Hoa\File\Exception\Exception {}
}
namespace Hoa\File {
class Link extends \Hoa\File\Link\Link {}
}
namespace Hoa\File {
class Temporary extends \Hoa\File\Temporary\Temporary {}
}
namespace Hoa {
class Acl extends \Hoa\Acl\Acl {}
}
namespace Hoa\Websocket {
class Exception extends \Hoa\Websocket\Exception\Exception {}
}
namespace Hoa\XmlRpc {
class Exception extends \Hoa\Xmlrpc\Exception\Exception {}
}
namespace Hoa\XmlRpc {
class Message extends \Hoa\Xmlrpc\Message\Message {}
}
namespace Hoa {
class Stringbuffer extends \Hoa\Stringbuffer\Stringbuffer {}
}
namespace Hoa {
class Mime extends \Hoa\Mime\Mime {}
}
namespace Hoa\Mime {
class Exception extends \Hoa\Mime\Exception\Exception {}
}
namespace Hoa {
class Zombie extends \Hoa\Zombie\Zombie {}
}
```

2015-02-11 08:51 UTC, camael24 commented on Bin/Stub.php
> +class Stub extends \Hoa\Console\Dispatcher\Kit {
I apply the same logic than atoum with the atoum-stub-generator, but i can do an error  :)

2015-02-11 08:56 UTC, Hywan commented
@camael24 “these modifications”

2015-02-11 08:57 UTC, Hywan commented on Bin/Stub.php
> +class Stub extends \Hoa\Console\Dispatcher\Kit {
But we are not atoum :-).

2015-02-11 08:57 UTC, Hywan commented
@camael24 I don't use an IDE but does it fit in the IDE's users' workflow?

2015-02-11 11:01 UTC, Metalaka commented
I think it can be useful (because I'm very lazy so I need a good auto-completion :).
But why adding support for IDE now when you plan to remove PHPDoc in favor of Praspel ?
(related to: https://github.com/hoaproject/Core/issues/65)

What about adding abstract/interface/trait/final ?
```
namespace Hoa {
abstract class Dispatcher extends \Hoa\Dispatcher\Dispatcher {}
}
namespace Hoa {
interface Router extends \Hoa\Router\Router {}
}
```
Could be done with [ReflexionClass::is*()](http://php.net/manual/en/class.reflectionclass.php).

2015-02-11 15:58 UTC, Hywan commented
@Metalaka This PR address a different problem than the (hypothetical) removal PHPDoc.

2015-03-26 19:18 UTC, Hywan commented
ping?

2015-03-26 20:59 UTC, Metalaka commented on Bin/Stub.php
> +                    $f[] = array('class' => str_replace('/', '\\', $name), 'alias' => $end);
To generate more specific/valid alias you can add a regex and use the `keyword` value on line 169.
```php
$class = str_replace('/', '\\', $name);
preg_match('#((?:abstract\s)?class|interface|trait)\s'.$class.'\s#', $raw, $keyword);
$f[] = [
    'class'   => $class,
    'alias'   => $end,
    'keyword' => $keyword[1]
];
```
So the generated code will be valid, until Hoa don't use `final` class ;)

2015-03-29 20:36 UTC, Metalaka commented on Bin/Stub.php
> +                    $f[] = array('class' => str_replace('/', '\\', $name), 'alias' => $end);
In Hoa, there may be more than one space between `class` keyword and class name.
eg: [`Hoa\Response`](https://github.com/hoaproject/Http/blob/master/Response/Response.php#L82).
```php
'#((?:abstract\s)?class|interface|trait)\s+'.$c.'\s#'
```

(However it's not [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#41-extends-and-implements).)

2015-03-29 20:59 UTC, Metalaka commented on Bin/Stub.php
> +        $hoaPath = 'hoa://Library/';
Hoa will resolve this in the following order and use the first it found.
* Data/Library/Hoathis/
* Data/Library/Hoa/
* vendor/Hoathis/
* vendor/Hoa/
So if Hoa find one of the three first directory the script will not work as expected.

Moreover, it cause problems with Windows :/

2015-07-06 15:40 UTC, Metalaka commented
Fix https://github.com/hoaproject/Core/issues/39

I worked on this today: https://github.com/hoaproject/Devtools/compare/master...Metalaka:alias
* CS fixed.
* Will generate more specific aliases (interface/abstract...)
* "read" loop has been refactored.

@Hywan Should I do a PR on `camael24:f/stub_generate` or else ?

2015-07-07 07:16 UTC, Hywan commented
@Metalaka Yup, make a PR on this PR. Except if @camael24 is too busy to merge your PR.

@camael24: Thoughts?

2015-07-07 07:25 UTC, camael24 commented
Make the PR on my PR i merge it as soon as possible :)

2015-07-07 07:30 UTC, camael24 commented
I juste rebase my PR on master :) and you can go :)

2015-07-07 11:54 UTC, Metalaka commented
Done.

2015-07-14 06:02 UTC, Hywan commented
And now?

2015-07-14 09:19 UTC, Metalaka commented
/ping @camael24 : https://github.com/camael24/Devtools/pull/1 are waiting you ;)
After that you could merge this PR.

2015-07-16 07:56 UTC, camael24 commented
Merged :) thanks @Metalaka

2015-07-16 08:14 UTC, Hywan commented on Bin/Stub.php
> +class Stub extends Console\Dispatcher\Kit
We should provide a more explicit name here, isn't it :smiley:?

2015-07-16 08:15 UTC, Hywan commented on Bin/Stub.php
> +                  break;
Add 2 spaces before `break;` (everywhere) please.

2015-07-16 08:15 UTC, Hywan commented on Bin/Stub.php
> +                  break;
Remove this `break;`, useless regarding the `return` statement.

2015-07-16 08:15 UTC, Hywan commented on Bin/Stub.php
> +        // READ
Useless comment.

2015-07-16 08:15 UTC, Hywan commented on Bin/Stub.php
> +            $pathName  = $file->getPathName();
One useless space before `=` symbols.

2015-07-16 08:16 UTC, Hywan commented on Bin/Stub.php
> +        // WRITE
Useless comment.

2015-07-16 08:16 UTC, Hywan commented on Bin/Stub.php
> +            $out .= '}' . "\n";
Simply:
```php
$out .=
    'namespace …' .
    $class['keyword'] …;
```

2015-07-16 08:17 UTC, Hywan commented on Bin/Stub.php
> +        echo 'Usage   : devtools:stub <options>', "\n",
```php
echo
    'Usage …',
    '…';
```

2015-07-16 08:17 UTC, Hywan commented on Bin/Stub.php
> +        ['stub',    Console\GetOption::REQUIRED_ARGUMENT, 's'],
`output` would be better than `stub`, thoughts?

2015-07-16 08:18 UTC, Hywan commented on Bin/Stub.php
> +        ['stub',    Console\GetOption::REQUIRED_ARGUMENT, 's'],
And since this is the most important option, it must come first in this list.

2015-07-16 09:17 UTC, camael24 commented
Any proposal for an new name ?

2015-07-16 09:35 UTC, Hywan commented
What is the goal of this command (rhetoric question)?

2015-07-16 09:46 UTC, Metalaka commented on Bin/Stub.php
> +        $dryRun = false;
cs: align `=` with `$verbose`

2015-07-16 09:52 UTC, Hywan commented on Bin/Stub.php
> +        $dryRun = false;
`hoa devtools:cs` must fix that normally.

2015-07-20 12:46 UTC, camael24 commented
I run `hoa devtools:cs` :) 

Its for use hoa with an IDE , atoum name that atoum/stub_generator i do the same :p

2015-07-20 16:33 UTC, Hywan commented
Well, sorry but the name is not correct. It's not meaningfull. Any proposal?

2015-07-20 17:57 UTC, camael24 commented
What do you think about `autocomplete`, `autocompletion`, 'helper_autocomplete`, 'ide_autocomplete` ? really hard for to to find one word for that :/

2015-07-21 06:17 UTC, Hywan commented
What about “unfold classnames”? Or better: “unfold entity names”?

2015-07-21 08:44 UTC, camael24 commented
name are too long for the command no ?
`hoa devtools:unfoldEntityNames`  ?

2015-07-21 09:31 UTC, Hywan commented
Nop :-p. Maybe “unfold entites” or “resolve entities” can be correct too.

2015-07-21 09:38 UTC, camael24 commented
I can't see how do this in the code causes how manage the space ? with _ ? there are conflict with \ no ?

2015-08-04 06:24 UTC, Hywan commented on Bin/Cs.php
> +        $processus = new Console\Processus('php '.$phpCsFixer, $arguments);
Huh?

2015-08-04 06:26 UTC, Hywan commented
@camael24 Correct, that's the https://github.com/hoaproject/Core/issues/57 issue. Never mind. Tell me what name you would like to choose and we will see how to format it.

2016-03-03 09:43 UTC, Hywan commented
What is the status of this PR?

2016-03-03 12:06 UTC, Metalaka commented
@Hywan @camael24 The feature is waiting for a name.

I vote for `resolve entities` or `resolve flex entities`

2016-03-03 20:31 UTC, camael24 commented
i am agree with `resolve flex entities`

2016-03-03 20:32 UTC, camael24 commented
ping @Hywan  see my previous comment

2016-03-08 18:39 UTC, Metalaka commented
@camael24 can you go ahead and change the name in the code?
Then @Hywan will merge it (and maybe rename the feature if he has a better name ;)

2016-03-09 07:44 UTC, Hywan commented
Resolving implies something that is not solved, so a problem to solve. There is no problem here. What about `unfold flex entities`?

2016-03-09 07:45 UTC, Hywan commented
Funny: https://github.com/hoaproject/Devtools/pull/6#issuecomment-123237559.

2016-03-12 10:50 UTC, Metalaka commented
@Hywan good for me too

2016-03-14 12:33 UTC, Hywan commented
Waiting on @camael24 so.

2017-02-17 08:30 UTC, Pierozi commented
@camael24 Have you time to finish this PR or did you want some help ?

2017-02-23 08:27 UTC, Pierozi requested changes
- [ ] Change the class name
- [ ] Increase description

2017-02-23 08:27 UTC, Pierozi commented on Bin/Stub.php
> +class Stub extends Console\Dispatcher\Kit
The vote name are `unfoldFlexEntities`

2017-02-23 08:27 UTC, Pierozi commented on Bin/Stub.php
> +Resolve class_alias function for the IDE.
A much specific description ? something like
`Create stub class of flex entities for enable auto completion on IDE`

2017-02-26 19:05 UTC, jubianchi commented
I don't think the word "unfold" is appropriate here.

Unfolding means, IMHO, that some things are grouped under a common item (folder containing files for example: when we unfold the directory we see files). Here we only have a single item under a single name: flex entity (alias) => actuel class.

I would rather use something like "expand": we go from a short name (flex entity alias) to a full name.

Expanding flex entities is done when we generate stubs of flex entity classes: we could have used "generate stubs" but it wouldn't be explicit about which stubs we generate. "expand flex entities" seems ok to me.

If you need help here, let me know I should have some time in the coming days.

2017-02-27 07:57 UTC, Hywan commented
:+1: for expand.

@jubianchi please, feel free to take this PR. I don't have time or energy to take it.

2017-02-27 08:35 UTC, Pierozi commented
So let's approve `ExpandFlexEntities` :+1: ( Choose a name can be very difficult )

2017-02-27 12:58 UTC, vonglasow commented
👍

2017-04-27 12:10 UTC, Pierozi commented
Closed like it was issued on #43

2017-04-27 12:10 UTC, closed without merging